### ISSUE TITLE
Error after edit or add

### ISSUE THREAD

**Issue by thehulk58** [marinantonio/angular-mat-table-crud#1]
**Right after when we update or add new item, it gives error "**
Cannot read property 'id' of undefined
    at eval (masters.designationcrud.component.ts:187)
    at Array.filter (<anonymous>)
    at MapSubscriber.eval [as project] (masters.designationcrud.component.ts:184)
    at MapSubscriber._next (map.js:79)
    at MapSubscriber.Subscriber.next (Subscriber.js:92)
    at MergeMapSubscriber.notifyNext (mergeMap.js:151)
    at InnerSubscriber._next (InnerSubscriber.js:25)
    at InnerSubscriber.Subscriber.next (Subscriber.js:92)
    at BehaviorSubject.Subject.next (Subject.js:56)
    at BehaviorSubject.next (BehaviorSubject.js:46)
"

**code line-**
 return Observable.merge(...displaydataChangeDesignation).map(() => {
       //Filter data
       this.filteredData = this._exampleDatabase.dataDesignation.slice().filter((designation: IDesignation) => {
         const searchStr = (designation.id + designation.designationName ).toString().toLowerCase();// this line gives error
         return searchStr.indexOf(this.filter.toLowerCase()) !== -1;
       });
         
       if we click reload data button then it binds newly added/updated value. I think the grid is loading data too fast before it gets data from the server and find nothing.Please suggest how can I correct this issue.

**Comment by marinantonio** [comment]
So If I get this right, your dataServices works fine, DB query passes but you have a problem with the frontend update? Does delete work? Well, looking at your error you have an issue with the ID. My best guess is that you're not passing ID correctly from dialog. Try assigning constant value to the ID and observe results.

**Comment by ramziakkari** [comment]
Do you have solution for this please? i have the same error

**Comment by marinantonio** [comment]
Same thing I wrote above. Please check your ID.

**Comment by vardhan2507** [comment]
https://github.com/marinantonio/angular-mat-table-crud/issues/3#issuecomment-368583860

Check this.... This is working like Pro!!! After searching a lot, finally found this fix.
