### ISSUE TITLE
Reading data from JSON - Beyond CRUD

### ISSUE THREAD

**Issue by ashasaji** [marinantonio/angular-mat-table-crud#10]
Hello,

I am a newbie to Angular and able to do my first trail with your working example. Thank you so much.

Have to improve my UI, with additional data -  Sample UI/ JSON attached.
1. I will have non-tabular data along with multiple no. of tabular data. (I will have multiple tables one after the other in the final UI.)
2. My first trial was sucessful - I had ONLY list of products in the  JSON and it was working properly. Then I have added additional data elements in JSON  n HTML as reflected in attached pic (like patient age/gender/country..etc). 
3. After the JSON update, without any code change, console showed the correct data on console (exampledatabase)
3. However MatTable earler populated with list of products is loosing data.

Pls help me..

** I do not know how to change data service/ model / loaddata()...etc according to new data. 
** Are there any additional changes reqd to accomplish above remnt?
** I will have to use more tables in the UI in similar manner - If so, JSON change followed by model and Html changes are sufficent?

Thanks in advance
ASHA
![ui with crud](https://user-images.githubusercontent.com/37214032/39878493-2249f7a4-5496-11e8-9697-d610023057e0.png)

**Comment by ashasaji** [comment]
Am adding pic of data service
![dataservice](https://user-images.githubusercontent.com/37214032/39911432-fded09d6-5518-11e8-818c-d9c41fb23d58.png)

**Comment by marinantonio** [comment]
Hello Asha,
I'm quite busy these days so I cannot dive much into your code. Few key things tho, MatTable data is stored into `this.exampleDatabase.dataChange.value` array. If you're making any changes make sure they end up there, and after doing operation call in refresh table function.  Debug that array in console and try to figure out what's happening.
Thanks

**Comment by ashasaji** [comment]
Thanks  Marian..!
