### ISSUE TITLE
Is this project updated with latest angular version i.e. angular?

### ISSUE THREAD

**Issue by vvavdiya** [marinantonio/angular-mat-table-crud#14]
In the latest version of angular material v6 `mat table` element is changed to `table`.
Is these demo is compatible with latest angular v6 and angular material v6?

**Comment by marinantonio** [comment]
I havent checked Angular 6 yet, but I don't there's much of a difference

**Comment by marinantonio** [comment]
I haven't checked Angular 6 yet, but I don't think there's much of a difference

**Comment by marinantonio** [comment]
@vvavdiya Not sure did you notice but updating Angular is such a stresfull thing to do and you always get mixed results. Anyway I did check it now, besides changes in angular material I've noticed some RxJS code should be rewritten as well. So this project **isn't at the moment** compatible with Angular v6.

**Comment by Folrond** [comment]
Actually the "core part" of this soulution that makes the table work can be copied into an angular 6 project and it works well it can be improved here and there but so far this is one of the better solutions for supporting crud in material table.

So the answer is:
1, No, it is not an out of the box angular 6 solution
2, Yes, the code works with angular 6

**Comment by vasilikivmo** [comment]
> @vvavdiya Not sure did you notice but updating Angular is such a stresfull thing to do and you always get mixed results. Anyway I did check it now, besides changes in angular material I've noticed some RxJS code should be rewritten as well. So this project **isn't at the moment** compatible with Angular v6.

Could you explain how you fixed the issue with RxJS? I am using Angular6, and even though I change the way I make the import, something doesn't go well... Thanks!

**Comment by marinantonio** [comment]
@vasilikivmo I still didn't, it requires a little bit of learning curve.

**Comment by vasilikivmo** [comment]
> @vasilikivmo I still didn't, it requires a little bit of learning curve.

I managed to do it. I had to modify the way I do the import of merge, fromEvent, BehaviorSubject inside my component and also make sure that both the versions of rxjs and rxjs-compat are updated

**Comment by ferhattelci** [comment]
Hey all i need help. Everything now works pretty well except for the data in the table. 
The data comes from a MongoDB. These are also loaded successfully, since I have looked with console.log afterwards.
I suspect my problem is with connect in the DataSource. There was an error in the observable merge, so I have changed it to combineLatest. Despite everything I get no data displayed .. this frustrates me a lot .. I would be very happy if you could help me

**Comment by marinantonio** [comment]
I've updated master as well. Key changes are below:

Updated rxjs imports
```
import {BehaviorSubject, fromEvent, merge, Observable} from 'rxjs';
import {map} from 'rxjs/operators';
```

And operators:

```
    return merge(...displayDataChanges).pipe(map( () => {
        // Filter data
        this.filteredData = this._exampleDatabase.data.slice().filter((issue: Issue) => {
          const searchStr = (issue.id + issue.title + issue.url + issue.created_at).toLowerCase();
          return searchStr.indexOf(this.filter.toLowerCase()) !== -1;
        });

        // Sort filtered data
        const sortedData = this.sortData(this.filteredData.slice());

        // Grab the page's slice of the filtered sorted data.
        const startIndex = this._paginator.pageIndex * this._paginator.pageSize;
        this.renderedData = sortedData.splice(startIndex, this._paginator.pageSize);
        return this.renderedData;
      }
    ));
}
```
