### ISSUE TITLE
Need Licensing details

### ISSUE THREAD

**Issue by karthyk16** [marinantonio/angular-mat-table-crud#15]
Hello - I want to use this component in my project which is on Angular 4 - Material 2. Can i use this component.? Will this cause issue as its on Angular 5.? 

Also - What is the licensing of this component to use in my project.

**Comment by marinantonio** [comment]
I don't think it will cause any issues, feel free to reuse this code without any licensing. This is simple project and I got most of ideas from [Stackoverflow](https://stackoverflow.com/questions/47443582/angular-material-table-is-it-possible-to-update-rows-without-entire-table-ref) anyway.

Cheers
