### ISSUE TITLE
Edit & Delete not works 

### ISSUE THREAD

**Issue by ferhattelci** [marinantonio/angular-mat-table-crud#16]
I get the error TypeError: undefined is not an object (evaluating 'repair.id') .
In this this.exampleDatabase.dataChange.value array is one data undefined .. this is be undefined after this line dialogRef.afterClosed().subscribe(result =>

**Comment by marinantonio** [comment]
I would check again repair.id, try to debug it logging repair.id through code.

**Comment by debugger22m** [comment]
Hi, 

I had the same issue. Can you verify the JSON data looks like? I had to something data[0].id for my case. Maybe try repair[0].id?
