### ISSUE TITLE
Filter throws exception after adding an issue.

### ISSUE THREAD

**Issue by simvn** [marinantonio/angular-mat-table-crud#17]
Hi all,

I have a slightly different implementation of your table. However, I think the same problem should occur here as well.

After adding an issue to my database, I am also adding it to my Behavior Subject (via .next(newissue) ). However, then the **slice** function crashes, since only the last emitted value is captured in my Behavior Subject value and not the whole array. 

>  this.filteredData = this._exampleDatabase.data.**slice().filter((**issue: Issue) => 

How do you suggest to deal with this?

Thanks a lot and best regards
Simon

**Comment by simvn** [comment]
Ok, I solved it like this right now:

> this.issueSubject.next(this.issueSubject.value.concat([newCost]));

Are there any other suggestions though?

**Comment by flcortesT** [comment]
Hi, I resolve this problem in the definition on table names of fields you need same names in variables. I fixed this problem.
