### ISSUE TITLE
How to add a functionality for individual column filter and column filtering

### ISSUE THREAD

**Issue by V2NileshSukalikar** [marinantonio/angular-mat-table-crud#2]
Hi , 

I would like to have a functionality which will display a filter above all the columns and which will filter individually. Also, Would be great if we can have functionality for individual column which can filter as per extra level of filter such as contains , equals to , >= , <= .

Also, Can you add something which can format the columns as well. Meaning , user can decide which columns to keep and which to not.

I am looking for something which is combination of below two grids 

https://l-lin.github.io/angular-datatables/#/advanced/individual-column-filtering 
This has got individual column filtering option 

https://ggmod.github.io/angular-2-data-table-demo/
This grid if you see have the option to filter the records , check top right side option. Which will show an popup and user can select which columns to keep

**Comment by V2NileshSukalikar** [comment]
Please add this functionalities which will make your grid more advance.

**Comment by marinantonio** [comment]
I'm using Angular Material DataTable found here:
https://material.angular.io/components/table/overview

Some things you suggested should be forwared to their core team so they can implement those into the component itself. Selecting displayed columns shouldn't be hard, you could try it for yourself. You need to use MatDialog with MatCheckBoxes and link them to the `displayedColumns ` found in app.component :

` displayedColumns = ['id', 'title', 'state', 'url', 'created_at', 'updated_at', 'actions'];`

Also you might want to consider how to save these states. Atm I have no free time to tinker with these but in near future I might try to develop things you suggested.

**Comment by V2NileshSukalikar** [comment]
Please try if you can develop as I am using your created CRUD table. 
You have uploaded very advanced grid component with all functionalities so would be great if I can use full functionalities within this. 

Thanks :-)

**Comment by marinantonio** [comment]
Sure, but if you manage to build up anything better before me feel free to pull changes. :)
