### ISSUE TITLE
Issue with Angular 8 loading

### ISSUE THREAD

**Issue by jai00271** [marinantonio/angular-mat-table-crud#20]
I am getting below error:

1. CreateCarsManiaComponent_Host.ngfactory.js? [sm]:1 ERROR TypeError: Cannot read property 'nativeElement' of undefined

2. core.js:7187 ERROR TypeError: Cannot set property 'pageIndex' of undefined

3. ERROR TypeError: Cannot read property 'sortChange' of undefined

Also since I am using angular 8, I had to change the code like:

  @ViewChild(MatPaginator, {static: false}) paginator: MatPaginator;
  @ViewChild(MatSort, {static: false}) sort: MatSort;
  @ViewChild('filter', {static: false}) filter: ElementRef;

I need help as I am the halfway of implementing this in my project and need to finish it soon.

**Comment by marinantonio** [comment]
Heya, I haven't worked with Angular 8 yet. I have to check what are the changes, and could things be built differently.
