### ISSUE TITLE
Can we use MatTableDataSource in your example?

### ISSUE THREAD

**Issue by LucaMurarolli** [marinantonio/angular-mat-table-crud#24]
Hi,

thanks for your code :). I'm pretty new to Angular and I did something like your example for my RESTful application using HttpService, Mat-Table and MatTableDataSource. Everything is working fine except that in Chrome my table scrollbar always scroll to bottom when I refresh my datasource. Do you know if it something related to MatTableDataSource? Did this happen to you also? 
MatTableDataSource extends DataSource so I think it should behave in the same way and in your example this issue does not appear.

This is my code, as you can see when I close the dialog I call the getLinedevices() method that update the dataSource. 
If, for example, I am deleting a record in the middle of the table after the datasource updates the scrollbar scrolls to the bottom.
This doesn't happen in firefox.

Any suggestions will be appretiated,

Thanks,
Luca
```
export class LinedeviceComponent implements OnInit {

  displayedColumns: string[] = [....];
  linedevices: Linedevice[];
  linedevice: Linedevice;
  dataSource = new MatTableDataSource(this.linedevices);
  lineId: number;
  deviceId: number;
  description: String;
`
  /**
   * HttpClientService 
   */
  constructor(
    private httpClientService: HttpClientService,
    private location: Location,
    public dialog: MatDialog,
    public deleteDialog: MatDialog,
    public insertDialog: MatDialog
  ) { }

  ngOnInit() {
    this.getLinedevices();
  }

getLinedevices() {
    this.httpClientService.getLinedevices().subscribe(
      response => this.dataSource.data = response,
    );
  }
/*
   * Dialog di Delete  
   */

  openDeleteDialog(): void {
    const dialogRef = this.deleteDialog.open(DialogDeleteComponent, {
      width: '500px',
      data: { lineId: this.lineId, deviceId: this.deviceId, description: this.description }
    });

    dialogRef.afterClosed().subscribe(result => {
      console.log('The delete dialog was closed');
      /*console.log(result);*/
      this.getLinedevices();
    });
  }
```

**Comment by marinantonio** [comment]
Hi @LucaMurarolli, sorry for late reply! I'm also fairly new to Angular and this was my only project in it. Are you able to recreate same issue on my demo?

https://marinantonio.github.io/angular-mat-table-crud/

**Comment by LucaMurarolli** [comment]
> Hi @LucaMurarolli, sorry for late reply! I'm also fairly new to Angular and this was my only project in it. Are you able to recreate same issue on my demo?
> 
> https://marinantonio.github.io/angular-mat-table-crud/

Hi,

thanks for your answer. I had the time to go more deep in the code ;).
I think is something normal that the scroll position it's not "saved" using MatTableDataSource as I did. 
The big difference between my test and your project is that you are pushing in the object that you have updated (by index), instead I was reloading all the data and re-assign the datasource.
I think in my case the only possobility is to save the scroll position in a variable and then apply the position after the table reloaded.

Hope to had clear it out ;)

Thanks,
Luca
