### ISSUE TITLE
addNew()

### ISSUE THREAD

**Issue by flcortesT** [marinantonio/angular-mat-table-crud#28]
I have this error message when I tried use addNew() function, Expected 1 arguments, but got 0.
 <button mat-icon-button color="accent" (click)="addNew()" >. I want to know how can I resolve this issue. Thanks

**Comment by ratnaraj16** [comment]
Any solution for this issue ? struck with same issue

**Comment by marinantonio** [comment]
@flcortesT , @ratnaraj16 It's been fixed in the latest PR #32
Thanks
