### ISSUE TITLE
Error while adding 

### ISSUE THREAD

**Issue by atmohsin** [marinantonio/angular-mat-table-crud#3]
ERROR TypeError: Cannot read property 'name' of undefined
    at eval (user.component.ts:174)
    at Array.filter (<anonymous>)
    at MapSubscriber.eval [as project] (user.component.ts:172)
    at MapSubscriber._next (map.js:79)
    at MapSubscriber.Subscriber.next (Subscriber.js:92)
    at MergeMapSubscriber.notifyNext (mergeMap.js:151)
    at InnerSubscriber._next (InnerSubscriber.js:25)
    at InnerSubscriber.Subscriber.next (Subscriber.js:92)
    at BehaviorSubject.Subject.next (Subject.js:56)
    at BehaviorSubject.next (BehaviorSubject.js:46)

This error occure when assigning the   dialogData with the object which we got it from form.
this.dialogData = userObj;

if we put before post request in Service class it is working, But id and created_at and update_at are emty, In my case ID is auto increament and created_at and update_at are set to default value current date. So user wont supply it from the front end. Once the user object persisted in to the data base. These value id,created_at and update_dt are should assign to the front end list.

Please suggest how we can overcome this.

Thanks
Mohsin

**Comment by marinantonio** [comment]
You might want to check out this or other samples how to retrieve current date/time:
http://embed.plnkr.co/1DtJB6nAAYp9ZXOcfP6P/

In my projects backend generates date and time.

**Comment by atmohsin** [comment]
dialogRef.afterClosed().subscribe(result => { 
      if (result === 1) {
        // After dialog is closed we're doing frontend updates
        // For add we're just pushing a new row inside DataService
        setTimeout(() => {
            this.exampleDatabase.dataChange.value.push(this.dataService.getDialogData());
            this.refreshTable();
        },2000);
      }
    });

I made some delay, so that the object get from API set it.

**Comment by marinantonio** [comment]
Does it works?

**Comment by atmohsin** [comment]
Yes

**Comment by kishore96182** [comment]
Use below code it's working!!!

 setTimeout(() => {
          this.exampleDatabase.dataChange.value.push(this.dataService.getDialogData());
          this.exampleDatabase.getAllIssues();
          this.refreshTable();
        }, 1500);
