### ISSUE TITLE
How to read data-source property values on component side 

### ISSUE THREAD

**Issue by V2NileshSukalikar** [marinantonio/angular-mat-table-crud#4]
Hi , 

This is something very urgent i need help on. 
We are sending value from datasource which gets bind to mat table. My question is how to read datasource values in typescipt file of that component. When i console.log(datssource) I able to see all those properties but unable to access them when i start accesing them using . operator in ts file. its returning me either undefined or empty.

Also, How to add extra properties during connect operation of datasource which can be read on component side.

**Comment by marinantonio** [comment]
Try:

`console.log(this.exampleDatabase.dataChange.value);`

Atm I don't have laptop with me and I cannot help you more
