### ISSUE TITLE
How to work with search , sorting and pagination when we have large number of records

### ISSUE THREAD

**Issue by V2NileshSukalikar** [marinantonio/angular-mat-table-crud#5]
Hi , 

Your code demonstration works great with limited data. My question is how to consider your logical code to be able to work with a large number of records.
As a general rule, we should never bring all lacks of records and bind it to the data source.

But if we are bringing limited records then during each activity such as sorting , filtering, pagination every time we have to call an API. Let me know how we can solve this problem with your logic written.

Thanks

**Comment by marinantonio** [comment]
Hi,

I've used this project for an asset management control where we have 40.000 rows, so it works there. Entire dataSource loads into browser so you won't strees server much.

If you wanna do that google something like "realtime updates angular mattable". Other guides and soultions will probably use sockets to achieve realtime updates and changes.

With regards,
Antonio Marin

**Comment by V2NileshSukalikar** [comment]
So, What do you think of limit of data source that we can attach to datssource at one shot.
Will it work perfectly fine if i bring the records from the server like 1 lakhs of records and more than that.

**Comment by marinantonio** [comment]
I'm not sure, also, attaching whole dataset to datasource can stress browser. You need a new pagination if you're going to do it like that. You can change entire code to use backend pagination and filter so you might wanna try that.

**Comment by V2NileshSukalikar** [comment]
Ok, I got your point. In your last comment, you had mentioned that you have used with 40k rows so asked if its possible that we can grab the data directly without any performance problem. 

Would be great if you can make this example real time.

**Comment by marinantonio** [comment]
From my experience you can grab data without any performance issues. I can't make a realtime example because I don't have any db up and running.
