### ISSUE TITLE
Handle errors durring Add/Delete/Edit Dialogs 

### ISSUE THREAD

**Issue by dmushkov** [marinantonio/angular-mat-table-crud#7]
Great example! Thanks for this gem!

How errors from Data Service can be handled while Dialog is already closed? 

Thanks

**Comment by marinantonio** [comment]
Please take a look at (especially commented part):
https://github.com/marinantonio/angular-mat-table-crud/blob/master/src/app/services/data.service.ts

We're using httpClient's error handling, `HttpErrorResponse`, so once you call one of the methods httpClient will tick error if it happened. It has nothing to do with dialog. Etc. PUT method:

  ```
 updateItem(kanbanItem: KanbanItem): void {
    this.httpClient.put(this.API_URL + kanbanItem.id, kanbanItem).subscribe(data => {
        this.dialogData = kanbanItem;
        console.log('Successuful, all fine');
      },
      (err: HttpErrorResponse) => {
        console.log('Error occurred. Details: ' + err.name + ' ' + err.message);
      }
    );
```

[Source](https://medium.com/codingthesmartway-com-blog/angular-4-3-httpclient-accessing-rest-web-services-with-angular-2305b8fd654b)

**Comment by dmushkov** [comment]
Hi @marinantonio and thanks for pointing this out. I tried this but now I stuck on dialogData variable.
I use angular/material:5.2.4. Behaviour of that version make that piece of code not work as expected.
It seems dialog is already closed but dataService has not yet finished - so push bellow gets wrong (old) value stored in `dialogData`
   
```
For add we're just pushing a new row inside DataService
 this.exampleDatabase.dataChange.value.push(this.dataService.getDialogData() );
```

gets dialogData before 

```
addItem(kanbanItem: SubscriptionDto): void {
        this.serviceProxy.create(kanbanItem).subscribe((result) => {
           ===>>>> this.dialogData = result; <<<<<=====
            this.toasterService.showToaster('Successfully added', 3000);
        }, err => {
            this.toasterService.showToaster('Error occurred. Details: ' + err.name + ' ' + err.message, 8000);
        });
    }

```

**Comment by marinantonio** [comment]
I've updated to latest material and I'm still unable to reproduce your issues. What I see from your snippet you're using `serviceProxy `? **HttpClient** uses HTTP Methods (POST, PUT, DELETE), so I'm not sure about create method? Also you might want to check backend response once operation passes. `HttpClient `usually expects some response and can break if there's none.
