### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by sharishkumar45** [marinantonio/angular-mat-table-crud#9]
How to make the toaster functional?
 Which toaster service are you using?

**Comment by marinantonio** [comment]
Basic [Snackbar](https://material.angular.io/components/snack-bar/overview) usage:

```
export class ToasterService {
  data: any;

  constructor(private snackBar: MatSnackBar) {
  }

  showToaster(message: string, duration: number) {
    this.snackBar.open(message, null, {
      duration: duration,
    });
  }
}
```

**Comment by sharishkumar45** [comment]
Thanks alot.. i had already done it.. forgot to update in the thread..
thanks for replying though.
